format = "$username in $hostname $localip: $directory\n$character"
right_format = "$all$time"

[time]
disabled = false
format = '[$time](gray)'

[character]
success_symbol = '\$'
error_symbol = '[\$](bold red)'
vimcmd_symbol = '[<](green)'

[username]
show_always = true
format = "[$user](bold yellow)"

[hostname]
ssh_only = false
format = "[$hostname](green)"

[localip]
disabled = false
ssh_only = false
format = '[\($localipv4\)](green)'

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
