[tools]
aws = "latest"
bat = "latest"
chezmoi = "latest"
dust = "latest"
eza = "latest"
fzf = "latest"
jq = "latest"
starship = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
